# Generated by Django 3.2.4 on 2021-06-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteTaking',
            new_name='Quote',
        ),
    ]
