# Generated by Django 3.2.7 on 2021-09-29 10:58

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_customer_migrations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quote',
            index=django.contrib.postgres.indexes.GinIndex(fields=['quote'], name='NewGinIndex', opclasses=['gin_trgm_ops']),
        ),
    ]
